name: gh-action-test2

dependencies:
- base > 4.14 && < 5

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - gh-action-test2
      - hspec == 2.*
      - hspec-junit-formatter >= 1.0.0.0
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*