name: gh-action-test

dependencies:
- base > 4.14 && < 5
- sbv

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - gh-action-test 
      - hspec == 2.*
      - hspec-junit-formatter >= 1.0.0.0
    vertabim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*