name: gh-action-test

dependencies:
- base > 4.14 && < 5

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - gh-action-test 
      - tasty
      - tasty-hunit
      - tasty-test-reporter
